// ─────────────────────────────────────────────
// lib/main.dart
// App entry point:
//   1. Initialize Firebase
//   2. Sign in anonymously
//   3. Init notifications
//   4. Route to PairingScreen or HomeScreen
//      (based on stored connection code)
// ─────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI
import 'screens/pairing_screen.dart';
import 'screens/home_screen.dart';
import 'services/firebase_service.dart';
import 'services/notification_service.dart';
import 'utils/constants.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── 1. Initialize Firebase ──
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // ── 2. Set up FCM & local notifications ──
  await NotificationService.initialize();

  // ── 3. Sign in anonymously ──
  await FirebaseService.signInAnonymously();

  // ── 4. Check for existing connection ──
  final prefs = await SharedPreferences.getInstance();
  final savedCode = prefs.getString(AppConstants.prefConnectionCode);

  // Lock to portrait mode
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);

  runApp(TouchLinkApp(savedCode: savedCode));
}

class TouchLinkApp extends StatelessWidget {
  final String? savedCode;
  const TouchLinkApp({super.key, this.savedCode});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TouchLink',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFFF6B9D),
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
        fontFamily: 'sans-serif',
      ),
      // Route based on whether user is already paired
      home: (savedCode != null && savedCode!.isNotEmpty)
          ? HomeScreen(connectionCode: savedCode!)
          : const PairingScreen(),
    );
  }
}
